apiVersion: apps/v1
kind: Deployment
metadata:
  name: fika-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fika-client
  template:
    metadata:
      labels:
        app: fika-client
    spec:
      containers:
        - name: fika-client
          image: ghcr.io/zhliau/fika-headless-docker:latest
          ports:
            - containerPort: 30698
              protocol: UDP
          env:
            - name: PROFILE_ID
              value: 689787450e4a99043400245b  # Replace with your actual profile ID
            - name: SERVER_URL
              value: fika-server
            - name: SERVER_PORT
              value: "30697"
            - name: AUTO_RESTART_ON_RAID_END
              value: "true"
            - name: ESYNC
              value: "true"
            - name: ENABLE_LOG_PURGE
              value: "true"
          volumeMounts:
            - name: client-storage
              mountPath: /opt/tarkov
      volumes:
        - name: client-storage
          hostPath:
            path: /home/brennan/spt-dedicated
---
apiVersion: v1
kind: Service
metadata:
  name: fika-client
spec:
  type: NodePort
  selector:
    app: fika-client
  ports:
    - protocol: UDP
      port: 30698
      targetPort: 30698
      nodePort: 30698
